/** Render a single page into a full HTML document */
export function layout(page) {
	return `<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="${page.description ?? ""}">
	<title>${page.title ?? page.name}</title>
</head>
<body>
	<main>${page.content}</main>
	<footer>Generated by <a href="https://sphido.cz">Sphido</a> from ${page.path}</footer>
</body>
</html>`;
}
