'use strict';

const {join} = require('path');
const {existsSync, outputFile} = require('fs-extra');
const {render, renderString} = require('../template');

const defaultPageTemplate = `<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>{{page.title}}</title>
</head>
<body>
	<main class="container">
		<article>{{page.content | trim | safe}}</article>
	</main>
	<!--
	Generated by Sphido https://www.sphido.org 
	{{page | dump(1)}} 
	-->	
</body>
</html>`;

module.exports = {
	/**
	 * Save page to file
	 * @param dir
	 * @param template
	 * @returns {Promise<*>}
	 */
	async save(dir, template) {
		template = template || this.template || 'theme/page.html';

		return await outputFile(
				join(dir, this.slug, 'index.html'),
				existsSync(template) ? render(template, {page: this}) : renderString(defaultPageTemplate, {page: this})
		);
	}

};